[package]
name = "torpedo"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 2
[dependencies]
libc = "0.2.172"
rand = "0.9.0"
raylib = {version = "5.5.1", features = ["with_serde"]}
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
serde_with = "3.12.0"
