files = main.cpp physics/col.cpp physics/physics.cpp level.cpp renderer/renderer.cpp ship/ship.cpp ship/player_ship.cpp
flags = -std=c++20  -O2
libs = -lraylib -L /opt/homebrew/opt/raylib/lib/
make: $(files)
	g++ $(files) $(flags) $(libs)
