files = main.cpp physics/col.cpp physics/physics.cpp level.cpp renderer/renderer.cpp  shaders.cpp
flags = -std=c++20  -O3
libs = -lraylib -L /opt/homebrew/opt/raylib/lib/
make: $(files)
	g++ $(files) $(flags) $(libs)
